---
- name: ensure mpd is installed
  package:
    name: "{{ item }}"
  with_items:
    - mpd
    - mpc

- name: ensure mpd is enabled and started when it should
  service:
    name: mpd
    enabled: "{{ mpd_autostart }}"
    state: "{% if mpd_autostart %}started{% else %}stopped{% endif %}"

- name: ensure mpd socket is enabled when it should
  service:
    name: mpd.socket
    enabled: "{% if mpd_autostart %}no{% else %}yes{% endif %}"
    state: "{% if mpd_autostart %}stopped{% else %}started{% endif %}"

- name: ensure mpd is configured
  template:
    src: mpd.conf.j2
    dest: /etc/mpd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart mpd

- name: ensure mpd port is open in firewall
  firewalld:
    port: 6600/tcp
    zone: "{{ item }}"
    permanent: true
    state: enabled
  with_items: "{{ mpd_firewall_zones }}"
